# Permalinks
permalink:        pretty

# Setup
title:            Mikhail Topolskiy
tagline:          ""
url:              https://whatthewhat.github.io
paginate:         1
baseurl:          ""
author:
  name:           Mikhail Topolskiy
  url:            https://twitter.com/what_a_what
  email:          mikhail.topolskiy@gmail.com

# Custom vars
version:          1.0.0

plugins:
  - jekyll-paginate
  - jekyll-redirect-from
