# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Mikhail Topolskiy
tagline:          ""
url:              http://whatthewhat.github.io
paginate:         1
baseurl:          /
author:
  name:           Mikhail Topolskiy
  url:            https://twitter.com/what_a_what
  email:          mikhail.topolskiy@gmail.com

# Custom vars
version:          1.0.0

gems:
  - jekyll-redirect-from
